src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $UserId = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Menu $MenuId = null;


    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_and_time_of_order = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?Plat $Type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->UserId;
    }

    public function setUserId(?User $UserId): static
    {
        $this->UserId = $UserId;

        return $this;
    }

    public function getMenuId(): ?Menu
    {
        return $this->MenuId;
    }

    public function setMenuId(?Menu $MenuId): static
    {
        $this->MenuId = $MenuId;

        return $this;
    }

    public function getDateAndTimeOfOrder(): ?\DateTimeInterface
    {
        return $this->date_and_time_of_order;
    }

    public function setDateAndTimeOfOrder(\DateTimeInterface $date_and_time_of_order): static
    {
        $this->date_and_time_of_order = $date_and_time_of_order;

        return $this;
    }

    public function getType(): ?Plat
    {
        return $this->Type;
    }

    public function setType(?Plat $Type): static
    {
        $this->Type = $Type;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $formation = null;

    /**
     * @var Collection<int, Menu>
     */
    #[ORM\ManyToMany(targetEntity: Menu::class, inversedBy: 'users')]
    private Collection $inscription;

    public function __construct()
    {
        $this->inscription = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getFormation(): ?string
    {
        return $this->formation;
    }

    public function setFormation(?string $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * @return Collection<int, Menu>
     */
    public function getInscription(): Collection
    {
        return $this->inscription;
    }

    public function addInscription(Menu $inscription): static
    {
        if (!$this->inscription->contains($inscription)) {
            $this->inscription->add($inscription);
        }

        return $this;
    }

    public function removeInscription(Menu $inscription): static
    {
        $this->inscription->removeElement($inscription);

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('password', PasswordType::class, [
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                // 'disabled'=> true ,
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
            ->add('nom')
            ->add('prenom')
            ->add('formation', null, [
                'attr' => ['class' => 'formation-field']
            ])
            ->add('roles', ChoiceType::class, [
                'choices'  => [
                    'Etudiant' => 'ROLE_STUDENT',
                    'Administration' => 'ROLE_ADMIN',
                ],
                'mapped' => false,
                'multiple' => false, 
                'expanded' => false,
                'attr' => ['id' => 'user_roles']  
            ]);
}

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'user_roles' => [],
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType; 
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\RedirectResponse;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository, Security $security): Response
    {
        $user = $security->getUser();
        if (!$this->isGranted('ROLE_ADMIN')) {
            return new RedirectResponse('/');
        }
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasher, Security $security): Response
    {
        $user = $security->getUser();
        if (!$this->isGranted('ROLE_ADMIN')) {
            return new RedirectResponse('/');
        }
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        $createdAt = new \DatetimeImmutable('now');

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setCreatedAt($createdAt);
            $user->setRoles([$form->get('roles')->getData()]);
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            
            $entityManager->persist($user);
            $entityManager->flush();
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
public function show(User $user, Security $security): Response
{
    if (!$this->isGranted('ROLE_ADMIN') && $user !== $security->getUser()) {
        return $this->redirectToRoute('/');
    }

    return $this->render('user/show.html.twig', [
        'user' => $user,
    ]);
}


    #[Route('/{id}/historique', name: 'app_user_show_historique', methods: ['GET'])]
    public function showhistorique(User $user, Security $security): Response
    {
        $user = $security->getUser();
        if (!$this->isGranted('ROLE_ADMIN')) {
            return new RedirectResponse('/');
        }
        return $this->render('user/showHistorique.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager, Security $security, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $currentUser = $security->getUser();
    
        if (!$this->isGranted('ROLE_ADMIN')) {
            if ($currentUser !== $user) {
                return new RedirectResponse('/');
            }
        }
        $currentUser->getRoles()[0];
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $newPassword = $form->get('password')->getData();
            if (!empty($newPassword)) {
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $newPassword
                    )
                );
            }
    
            if ($this->isGranted('ROLE_ADMIN')) {
                $user->setRoles([$form->get('roles')->getData()]);
            }
    
            $entityManager->flush();
    
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }
    
        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
    


    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $userToDelete, EntityManagerInterface $entityManager, Security $security): Response
    {
        $currentUser = $security->getUser();
        if (!$this->isGranted('ROLE_ADMIN', $currentUser)) {
            return new RedirectResponse('/');
        }
        
        if ($this->isCsrfTokenValid('delete' . $userToDelete->getId(), $request->request->get('_token'))) {
            $entityManager->remove($userToDelete);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">

	<button class="btn btn-danger">
		<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewbox="0 0 16 16">
			<path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z"/>
		</svg>
		Supprimer
	</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-success">{{ button_label|default('') }}
	<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check2" viewbox="0 0 16 16">
		<path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0"/>
	</svg>
	Enregistrer
</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User
{% endblock %}
{% block page_name %}
	Modification Utilisateur
{% endblock %}

{% block body %}

	<style>
		a {
			margin-bottom: 15px;
		}

		#edit_user_button {
			display: flex;
			justify-content: space-between;
		}
	</style>

	{{ form_errors(form) }}

	{{ form_start(form, {'attr': {'class': 'needs-validation', 'id': 'form_new_user'}}) }}
	{% if is_granted('ROLE_ADMIN') %}
		<a href="{{ path('app_user_index') }}" class="btn btn-primary">
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewbox="0 0 16 16">
				<path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"></path>
			</svg>
			Retour liste utilisateurs
		</a>
	{% endif %}

	<div class="row">
		<div class="col-md-6 mb-3">
			{{ form_label(form.nom, null, {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="col-md-6 mb-3">
			{{ form_label(form.prenom, null, {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="col-md-6 mb-3">
			{{ form_label(form.email, null, {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="col-md-6 mb-3">
			{{ form_label(form.password, null, {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.password, {'attr': {'class': 'form-control'}}) }}
		</div>
		{% if is_granted('ROLE_ADMIN') %}
			<div class="col-md-6 mb-3">
				{{ form_label(form.roles, null, {'label_attr': {'class': 'form-label'}}) }}
				{{ form_widget(form.roles, {'attr': {'class': 'form-control'}}) }}
			</div>
			<div class="col-md-6 mb-3">
				{{ form_label(form.formation, null, {'label_attr': {'class': 'form-label'}}) }}
				{{ form_widget(form.formation, {'attr': {'class': 'form-control'}}) }}
			</div>
		{% endif %}


	</div>
	{% if is_granted('ROLE_STUDENT')  %}
		<div id="additional-fields" style="display: none; margin-bottom: 15px;">
			{{ form_label(form.roles, null, {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.roles, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div id="additional-fields" style="display: none; margin-bottom: 15px;">
			{{ form_label(form.formation, null, {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.formation, {'attr': {'class': 'form-control'}}) }}
		</div>
	{% endif %}

	<div id="edit_user_button">
		<div>
			{{ include('user/_form.html.twig', {'button_label': ''}) }}
		</div>
		<div>
			{{ include('user/_delete_form.html.twig') }}
		</div>
	</div>

	{{ form_end(form) }}

{% endblock %}

templates/user/showHistorique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande us
{% endblock %}
{%block page_name %}
	{{user.nom}}
	{{user.prenom}}
{% endblock %}

{% block body %}

	<style>
		div {
			display: flex;
			margin: 10px;
		}

		div a {
			margin-right: 10px;
		}
	</style>

	<table class="table" id="users-inscription">
		<thead>
			<tr>
				<th>Date</th>
				<th>Service</th>
				<th>Type de plat séléctionner</th>
				<th class="hideInExcel">Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for commande in commandes %}
				<tr>
					<td>{{ commande.dateAndTimeOfOrder|date("Y-m-d H:i:s") }}</td>
					<td>{{ commande.MenuId.id }}</td>
					<td>{{ commande.Type.regime }}</td>
					<td class="hideInExcel">
						<a href="{{ path('app_commande_edit',{'id': user.id}) }}" class="btn btn-warning">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewbox="0 0 16 16">
								<path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
								<path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
							</svg>
							Modifier
						</a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<div>
		<a href="{{ path('app_user_index') }}" class="btn btn-primary">
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewbox="0 0 16 16">
				<path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5"></path>
			</svg>
			Retour liste utilisateurs
		</a>

		<a onclick="exportToExcel()" class="btn btn-success">
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-filetype-xlsx" viewbox="0 0 16 16">
				<path fill-rule="evenodd" d="M14 4.5V11h-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5zM7.86 14.841a1.13 1.13 0 0 0 .401.823q.195.162.479.252.284.091.665.091.507 0 .858-.158.355-.158.54-.44a1.17 1.17 0 0 0 .187-.656q0-.336-.135-.56a1 1 0 0 0-.375-.357 2 2 0 0 0-.565-.21l-.621-.144a1 1 0 0 1-.405-.176.37.37 0 0 1-.143-.299q0-.234.184-.384.188-.152.513-.152.214 0 .37.068a.6.6 0 0 1 .245.181.56.56 0 0 1 .12.258h.75a1.1 1.1 0 0 0-.199-.566 1.2 1.2 0 0 0-.5-.41 1.8 1.8 0 0 0-.78-.152q-.44 0-.777.15-.336.149-.527.421-.19.273-.19.639 0 .302.123.524t.351.367q.229.143.54.213l.618.144q.31.073.462.193a.39.39 0 0 1 .153.326.5.5 0 0 1-.085.29.56.56 0 0 1-.255.193q-.168.07-.413.07-.176 0-.32-.04a.8.8 0 0 1-.249-.115.58.58 0 0 1-.255-.384zm-3.726-2.909h.893l-1.274 2.007 1.254 1.992h-.908l-.85-1.415h-.035l-.853 1.415H1.5l1.24-2.016-1.228-1.983h.931l.832 1.438h.036zm1.923 3.325h1.697v.674H5.266v-3.999h.791zm7.636-3.325h.893l-1.274 2.007 1.254 1.992h-.908l-.85-1.415h-.035l-.853 1.415h-.861l1.24-2.016-1.228-1.983h.931l.832 1.438h.036z"/>
			</svg>
			Télécharger
		</a>

		{{ include('user/_delete_form.html.twig') }}
	</div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.0/FileSaver.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.5/xlsx.full.min.js"></script>
	<script>
		function exportToExcel() {
var table = document.getElementById("users-inscription");
if (! table) {
console.error('La table n\'a pas été trouvée.');
return;
}

var wb = XLSX.utils.book_new(); // workbook
var ws = XLSX.utils.table_to_sheet(table);
// table to sheet

for (var i = 0; i < table.rows.length; i++) {
var row = table.rows[i];
for (var j = 0; j < row.cells.length; j++) {
var cellElement = row.cells[j];
var cellAddress = XLSX.utils.encode_cell({r: i, c: j});
var cell = ws[cellAddress];
if (cellElement.classList.contains('hideInExcel')) {
delete ws[cellAddress];
}
}
}

XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');

var wbout = XLSX.write(wb, {
bookType: 'xlsx',
type: 'binary'
});
saveAsExcelFile(wbout, "{{ user.nom|replace({' ': '_', '/': '_', '\\\\': '_'}) }}-{{ user.prenom|replace({' ': '_', '/': '_', '\\\\': '_'}) }}_Inscription.xlsx");
}

function saveAsExcelFile(buffer, fileName) {
var blob = new Blob([s2ab(buffer)], {type: "application/octet-stream"});
var url = window.URL.createObjectURL(blob);
var link = document.createElement("a");
link.href = url;
link.setAttribute("download", fileName);
document.body.appendChild(link);
link.click();
document.body.removeChild(link);
}

function s2ab(s) {
var buf = new ArrayBuffer(s.length);
var view = new Uint8Array(buf);
for (var i = 0; i < s.length; i++) 
view[i] = s.charCodeAt(i) & 0xFF;



return buf;
}
	</script>


{% endblock %}